# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Datetime', models.DateTimeField()),
                ('Path', models.CharField(max_length=30)),
                ('Tag', models.CharField(max_length=30)),
            ],
        ),
    ]
