# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Datetime', models.DateTimeField()),
                ('Path', models.CharField(max_length=30)),
                ('Tag', models.CharField(max_length=30)),
                ('RenamePath', models.CharField(max_length=30)),
            ],
        ),
    ]
