# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-12 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0005_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestELimg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_el_path', models.CharField(max_length=50)),
                ('constract_el_path', models.CharField(max_length=50)),
                ('rectangle_el_path', models.CharField(max_length=50)),
                ('tzqt_el_path', models.CharField(max_length=50)),
                ('dytzqt_el_path', models.CharField(max_length=50)),
                ('dytz_el_path', models.CharField(max_length=50)),
                ('el_type', models.CharField(max_length=50)),
            ],
        ),
    ]
