# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-12 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0007_testeltype'),
    ]

    operations = [
        migrations.AddField(
            model_name='testeltype',
            name='dytzqt_el_path',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
